   FROM php:8.1-fpm


   RUN docker-php-ext-install pdo pdo_mysql

  
   COPY . /var/www

   WORKDIR /var/www

   
   RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
   